### ISSUE TITLE
Run Oscar with Pytorch1.7 and Cuda10.1

### ISSUE THREAD

**Issue by rachs** [microsoft/Oscar#142]
Can I run Oscar with Pytorch 1.7 and cuda 10.1? I want to run the scenegraph benchmark repo to create object features and oscar to generate image captions from the same virtualenv. Has anyone done this?

**Comment by jontooy** [comment]
Hi rachs,

I'm working on a similar project and have spent alot of time on installing environments for Oscar. Their INSTALL.md file indeed states requirements

+ Pytorch 1.2
+ torchvision 0.4.0
+ cuda 10.0

I've managed to install both Oscar and sgg_benchmark using the same version of Pytorch (1.7.1) and Cuda (10.1). See this [demo repo](https://github.com/jontooy/vl_demos), so I think it might be possible to run them on the same virtualenv! Some files, and pretrained models might have to be downloaded from the respective repos in order to make the demos work.

Hope it helped! Good luck with your project and let me know how it goes :)

**Comment by rachs** [comment]
Didn't see this till now, thank you jontooy! Yes it worked for me with cuda 10.1 too.
