### ISSUE TITLE
gcc version

### ISSUE THREAD

**Issue by mireiahernandez** [microsoft/Oscar#31]
I get the error "command 'gcc' failed with exit status 1" when running the line of INSTALL.md "python setup.py install --cuda_ext --cpp_ext"

What gcc version do you use?

**Comment by xjli** [comment]
This is an error usually caused by CUDA version, pytorch version and apex lib.

You need to check your pytorch version first. 
if you are using CUDA 10.1 and torch=1.5.0+cu101, it is better to add this line to revert the apex to an older checkpoint, 

git checkout f3a960f80244cf9e80558ab30f7f7e8cbf03c0a0

then, run 
python setup.py install --cuda_ext --cpp_ext

Here are some configs which work from my side:

Config 1:
CUDA 10.1, torch==1.4.0
Apex: (no need that line)

Config 2:
CUDA 10.1, torch==1.5.0+cu101
Apex: needs that line. 

---------------------
Anther trick here is:
You can always install this first,
CUDA 10.1, torch==1.4.0
Apex: (no need that line)

If you need higher version of pytorch, say 1.5, you can install here (after Apex).
pip install torch==1.5.0 torchvision==0.6.0
So, you will not meet that compatibility issue.

Thanks,

**Comment by xjli** [comment]
@jaeyun95, if you still struggle with that issue, here are some suggestions for install config.

**Comment by mireiahernandez** [comment]
Thanks, that solved my problem. Also congrats on the great work!
